apiVersion: v1
kind: Service
metadata:
  name: mt-serving-service
  namespace: default
  labels:
    app: mt-serving
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 80
    nodePort: 30001
    protocol: TCP
    name: mt-serving-http
  selector:
    app: mt-serving